### ISSUE TITLE
url非纯英文出现的问题

### ISSUE THREAD

**Issue by HunterYIboHu** [XIAZY/DriveIt#2]
实验漫画网址：

```
http://www.dm5.com/manhua-fangxuehoudefengbaoguanxianledui/
```

实验过程

```
PS E:\LearnPython\DriveIt> python3 .\driveit.py
URL?
http://www.dm5.com/manhua-fangxuehoudefengbaoguanxianledui/
Where to save?
E:\BaiduYunDownload\漫画\
```

实验结果：

```
放学后的风暴管弦乐队, total 5 chapters detected.
Traceback (most recent call last):
  File ".\driveit.py", line 67, in <module>
    main_loop(ref_box)
  File ".\driveit.py", line 12, in main_loop
    website_object.down(comic_name, parent_link, link, title, page)
  File "E:\LearnPython\DriveIt\sites.py", line 94, in down
    img_data = self.get_data(link, 'http://www.dm5.com%s' % parent_link)
  File "E:\LearnPython\DriveIt\base.py", line 23, in get_data
    web_page = request.urlopen(req)
  File "E:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python34\lib\urllib\request.py", line 463, in open
    response = self._open(req, data)
  File "E:\Python34\lib\urllib\request.py", line 481, in _open
    '_open', req)
  File "E:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "E:\Python34\lib\urllib\request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "E:\Python34\lib\urllib\request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "E:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "E:\Python34\lib\http\client.py", line 1116, in _send_request
    self.putrequest(method, url, **skips)
  File "E:\Python34\lib\http\client.py", line 973, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-21: ordinal not in rang
e(128)
```

问题：**URL中有中文**。  
因为我用firebug查看了网页元素，发现这个图片的网址是：`http://manhua1014.61-147-113-113.cdndm5.com/f/放学后的风暴管弦乐队/放学后的风暴管弦队_ch01/000001_fb457d98.jpg?cid=49096&key=acd841ae172b8fa7b82c1a60d545f8ae`。  
解决方案：
我等会尝试着用PR试一下……我自己不会弄，原理在这里：[知乎——urlopen的中文问题](http://www.zhihu.com/question/22899135)

**Comment by XIAZY** [comment]
好……等会去调试一下，我用的时候倒没出过这个问题

**Comment by XIAZY** [comment]
手头没有电脑，试试这个

http://stackoverflow.com/questions/4389572/how-to-fetch-a-non-ascii-url-with-python-urlopen

Sent from Outlook Mobile

**Comment by XIAZY** [comment]
正在解决这个问题。测试发现使用 GUI 程序则没有这个问题，原因未知……

**Comment by XIAZY** [comment]
已修复。
